#include <stdbool.h>
#include <stddef.h>

extern void blankUI_draw_modal(int width, int height, char* title, char* content);
extern void blankUI_animate_fade_in(void* component);
extern int get_total_ram(void);

// The Out Of Box Experience (OOBE) state
typedef enum {
    STATE_HARDWARE_CHECK,
    STATE_WELCOME_ANIMATION,
    STATE_TERMS_AND_CONDITIONS,
    STATE_PARTITIONING,
    STATE_FONT_SELECTION,
    STATE_PROFILE_PICTURE,
    STATE_COMPLETE
} SetupState;

static SetupState current_state = STATE_HARDWARE_CHECK;

void setup_hardware_check(void) {
    // 1. Check RAM (Minimum 2GB / 2048MB required)
    int total_ram = get_total_ram();
    // 2. Check Storage (Minimum 20GB required - Stubbed to 25GB)
    int total_storage_gb = 25; 
    
    if (total_ram < 2048 || total_storage_gb < 20) {
        blankUI_draw_modal(
            600, 400, 
            "Installation Failed", 
            "Your system does not meet the minimum requirements for BlankOS.\n\nMinimum Requirements:\n- 2GB RAM\n- 20GB Storage\n- 64-bit CPU\n\nSetup cannot continue."
        );
        // Halt system permanently
        while(1) { __asm__ volatile("cli; hlt"); }
    }
    
    current_state = STATE_WELCOME_ANIMATION;
}

void setup_render_welcome_animation(void) {
    blankUI_animate_fade_in(NULL);
    current_state = STATE_TERMS_AND_CONDITIONS;
}

void setup_render_terms(void) {
    blankUI_draw_modal(
        800, 600, 
        "BlankOS Terms and Conditions", 
        "Welcome to BlankOS.\n\nPlease read the following terms:\nThis was generated by gemini.\n\nDo you accept these terms?"
    );
    // On accept:
    // current_state = STATE_PARTITIONING;
}

void setup_render_partitioning(void) {
    blankUI_draw_modal(
        800, 600,
        "Disk Partitioning",
        "Select how you want to install BlankOS:\n\n1. Erase Disk and Install (Automatic)\n   - Creates 512MB EFI System Partition\n   - Creates 4GB Swap Partition\n   - Creates Root (ext4/custom) Partition\n\n2. Manual Partitioning (Advanced)\n\nWARNING: This will erase data on the selected drive."
    );
    // Render blankUI buttons for selection
    // On complete:
    // current_state = STATE_FONT_SELECTION;
}

void setup_render_fonts(void) {
    blankUI_draw_modal(800, 600, "Select System Font", "Please choose your preferred typography style for the OS.");
}

void setup_render_profile(void) {
    blankUI_draw_modal(800, 600, "Choose a Profile Picture", "Select an avatar for your user account.");
}

void launch_setup_screen(void) {
    while (current_state != STATE_COMPLETE) {
        switch (current_state) {
            case STATE_HARDWARE_CHECK: setup_hardware_check(); break;
            case STATE_WELCOME_ANIMATION: setup_render_welcome_animation(); break;
            case STATE_TERMS_AND_CONDITIONS: setup_render_terms(); break;
            case STATE_PARTITIONING: setup_render_partitioning(); break;
            case STATE_FONT_SELECTION: setup_render_fonts(); break;
            case STATE_PROFILE_PICTURE: setup_render_profile(); break;
            default: break;
        }
    }
}
