#include <stdbool.h>
#include <stddef.h>

extern void blankUI_draw_modal(int width, int height, char* title, char* content);
extern void blankUI_animate_fade_in(void* component);

// The Out Of Box Experience (OOBE) state
typedef enum {
    STATE_WELCOME_ANIMATION,
    STATE_TERMS_AND_CONDITIONS,
    STATE_FONT_SELECTION,
    STATE_PROFILE_PICTURE,
    STATE_COMPLETE
} SetupState;

static SetupState current_state = STATE_WELCOME_ANIMATION;

void setup_render_welcome_animation(void) {
    // Clear screen to black
    // Fade in text: "welcome to blankOS, powered by blankUI"
    // Wait 2 seconds
    // Fade out text
    
    // Stub animation
    blankUI_animate_fade_in(NULL);
    
    // Automatically transition to terms
    current_state = STATE_TERMS_AND_CONDITIONS;
}

void setup_render_terms(void) {
    blankUI_draw_modal(
        800, 600, 
        "BlankOS Terms and Conditions", 
        "Welcome to BlankOS.\n\nPlease read the following terms:\nThis was generated by gemini.\n\nDo you accept these terms?"
    );
    // Draw Accept/Decline buttons using blankUI
}

void setup_render_fonts(void) {
    blankUI_draw_modal(
        800, 600, 
        "Select System Font", 
        "Please choose your preferred typography style for the OS."
    );
    // Render font list using blankUI
}

void setup_render_profile(void) {
    blankUI_draw_modal(
        800, 600, 
        "Choose a Profile Picture", 
        "Select an avatar for your user account."
    );
    // Render profile picture grid using blankUI
}

void launch_setup_screen(void) {
    while (current_state != STATE_COMPLETE) {
        switch (current_state) {
            case STATE_WELCOME_ANIMATION:
                setup_render_welcome_animation();
                break;
            case STATE_TERMS_AND_CONDITIONS:
                setup_render_terms();
                // Wait for user to accept, then advance state
                break;
            case STATE_FONT_SELECTION:
                setup_render_fonts();
                break;
            case STATE_PROFILE_PICTURE:
                setup_render_profile();
                break;
            default:
                break;
        }
    }
}
